
name: Amazon Homepage CI/CD

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t amazon-homepage .

      - name: Test Docker Container
        run: |
          docker run -d --name amazon-test -p 8080:80 amazon-homepage
          sleep 5
          curl http://localhost:8080

      - name: Stop Test Container
        run: |
          docker stop amazon-test
          docker rm amazon-test

